export const StatusAttachmentsXTF = {
  ACCEPTED_TEXT: 'ACEPTADO',
  IN_VALIDATION_TEXT: 'EN VALIDACIÓN',
  REJECTED_TEXT: 'RECHAZADO',
  ACCEPTED: 'ACCEPTED',
  IN_VALIDATION: 'IN_VALIDATION',
  REJECTED: 'REJECTED',
};
