export const StatusAttachmentsXTF = {
  ACCEPTED_TEXT: 'ACEPTADO',
  IN_VALIDATION_TEXT: 'EN VALIDACIÓN',
  REJECTED_TEXT: 'RECHAZADO',
  ACCEPTED: 'ACCEPTED',
  IN_VALIDATION: 'IN_VALIDATION',
  REJECTED: 'REJECTED',
  EN_CONTROL_CALIDAD: 'QUALITY_PROCESS_IN_VALIDATION',
  FINALIZADO_CALIDAD: 'QUALITY_PROCESS_FINISHED',
  EN_CONTROL_CALIDAD_TEXT: 'EN CONTROL DE CALIDAD',
  FINALIZADO_CALIDAD_TEXT: 'CONTROL DE CALIDAD FINALIZADO',
};
