// Generated by https://quicktype.io

export interface DecodedTokenInterface {
  access_token: string;
  token_type: string;
  refresh_token: string;
  expires_in: number;
  scope: string[];
  roles: Role[];
  last_name: string;
  first_name: string;
  email: string;
  entity: Entity;
  jti: string;
}

export interface Entity {
  id: number;
  name: string;
  taxIdentificationNumber: string;
  createdAt: string;
  alias: string;
  isPublic: boolean;
}

export interface Role {
  id: number;
  name: string;
}
