export const StateDeliveriesEnum = {
    DRAFT: 'DRAFT',
    SENT_CADASTRAL_AUTHORITY: 'SENT_CADASTRAL_AUTHORITY',
    IN_QUEUE_TO_IMPORT: 'IN_QUEUE_TO_IMPORT',
    IMPORTING: 'IMPORTING',
    SUCCESS_IMPORT: 'SUCCESS_IMPORT',
    FAILED_IMPORT: 'FAILED_IMPORT',
}