export const StateFilesEnum = {
    IN_VALIDATION: 'IN_VALIDATION',
    SUCCESSFUL: 'SUCCESSFUL',
    UNSUCCESSFUL: 'UNSUCCESSFUL',
    IMPORTING: 'IMPORTING',
    IMPORT_SUCCESSFUL: 'IMPORT_SUCCESSFUL',
    IMPORT_UNSUCCESSFUL: 'IMPORT_UNSUCCESSFUL'
}