// Generated by https://quicktype.io

export interface GetPendingRequestsPaginate {
  items:            Item[];
  currentPage:      number;
  numberOfElements: number;
  totalElements:    number;
  totalPages:       number;
  size:             number;
}

export interface Item {
  id:              number;
  closedAt:        null;
  closedBy:        null;
  createdAt:       number;
  deadline:        number;
  observations:    null;
  orderNumber:     string;
  status:          Status;
  manager:         Manager;
  federation:      Federation;
  suppliesSummary: SuppliesSummary[];
}

export interface Federation {
  code:         string;
  municipality: string;
  state:        string;
}

export interface Manager {
  code:  number;
  name:  string;
  alias: string;
}

export interface Status {
  id:   number;
  name: string;
}

export interface SuppliesSummary {
  id:   number;
  name: string;
  area: Area;
}

export enum Area {
  Agrología = "AGROLOGÍA",
  Cartografía = "CARTOGRAFÍA",
  Catastro = "CATASTRO",
}
